# Generated by Django 3.0.3 on 2022-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='economic_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='کد اقتصادی'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='شناسه ملی'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='شماره ثبت'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='شماره تلفن ثابت'),
        ),
        migrations.AddField(
            model_name='user',
            name='warehouse_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='آدرس محل انبار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=256, unique=True, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='کد معرف'),
        ),
    ]
