# Generated by Django 4.0.2 on 2022-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal',
            field=models.BooleanField(default=False, verbose_name='شخصیت حقوقی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس'),
        ),
    ]
