# Generated by Django 4.0.2 on 2022-02-17 09:43

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='والد', to='shop.category', verbose_name='والد'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='logos/default.png', upload_to='logos', verbose_name='لوگو فروشگاه'),
        ),
    ]
