# Generated by Django 4.0.2 on 2022-02-17 10:59

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_parent_alter_shop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_category', to='shop.category', verbose_name='دسته بند'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('code', models.CharField(max_length=50, verbose_name='کد محصول')),
                ('name', models.CharField(max_length=80, verbose_name='نام محصول')),
                ('image', models.ImageField(default='products/default.png', upload_to='products', verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('qty', models.IntegerField(verbose_name='تعداد')),
                ('brand', models.CharField(max_length=50, verbose_name='برند محصول')),
                ('link', models.URLField(verbose_name='لینک محصول')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات')),
                ('datasheet', models.FileField(max_length=254, upload_to='datasheet', verbose_name='فایل و Datasheet')),
                ('date_created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='shop.category', verbose_name='دسته بند')),
                ('provider_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shop.shop', verbose_name='فروشگاه ارائه دهنده')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
