# Generated by Django 3.0.3 on 2022-04-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='userimg/default.png', upload_to='userimg', verbose_name='تصویر'),
        ),
    ]
