# Generated by Django 3.0.3 on 2022-08-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='شماره حساب'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AddField(
            model_name='user',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='شماره شبا'),
        ),
    ]
