# Generated by Django 3.0.3 on 2022-05-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='لینک محصول'),
        ),
    ]
