# Generated by Django 3.0.3 on 2022-05-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='ویژگی'),
        ),
    ]
