# Generated by Django 3.0.3 on 2022-05-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopproducts',
            old_name='wholesale_price',
            new_name='three_price',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='medium_volume_price',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='min_medium_num',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='min_wholesale_num',
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='min_three_qty',
            field=models.IntegerField(default=0, verbose_name='حداقل سه قیمتی'),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='min_two_qty',
            field=models.IntegerField(default=0, verbose_name='حداقل دو قیمتی'),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='one_price',
            field=models.IntegerField(default=0, verbose_name='قیمت تکی'),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='two_price',
            field=models.IntegerField(default=0, verbose_name='دو قیمتی'),
        ),
    ]
