# Generated by Django 3.0.3 on 2022-08-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='central_office_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='central_office_city', to='shop.City', verbose_name='شهر دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='shop',
            name='central_office_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='central_office_province', to='shop.Province', verbose_name='استان دفتر مرکزی'),
        ),
        migrations.AddField(
            model_name='shop',
            name='landline_phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره تماس ثابت'),
        ),
    ]
