# Generated by Django 3.0.3 on 2022-04-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='aaa',
            field=models.CharField(blank=True, default='aaa', max_length=20, null=True),
        ),
    ]
