# Generated by Django 3.0.3 on 2022-05-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default.png', null=True, upload_to='vovers', verbose_name='کاور فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, default='logos/default.png', null=True, upload_to='logos', verbose_name='لوگو فروشگاه'),
        ),
    ]
