# Generated by Django 3.0.3 on 2022-05-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220505_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproducts',
            name='retail_price',
        ),
    ]
