# Generated by Django 3.0.3 on 2022-04-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_aaa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='aaa',
        ),
    ]
