# Generated by Django 3.0.3 on 2022-05-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220510_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproducts',
            name='min_three_qty',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='min_two_qty',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='three_price',
        ),
        migrations.RemoveField(
            model_name='shopproducts',
            name='two_price',
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='medium_volume_price',
            field=models.IntegerField(default=0, verbose_name='قیمت حجم متوسط'),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='medium_volume_qty',
            field=models.IntegerField(default=0, verbose_name='حداقل تعداد حجم متوسط'),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='wholesale_volume_price',
            field=models.IntegerField(default=0, verbose_name='قیمت حجم عمده'),
        ),
        migrations.AddField(
            model_name='shopproducts',
            name='wholesale_volume_qty',
            field=models.IntegerField(default=0, verbose_name='حداقل تعداد حجم عمده'),
        ),
    ]
