# Generated by Django 3.0.3 on 2022-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220515_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default.png', null=True, upload_to='covers', verbose_name='کاور فروشگاه'),
        ),
    ]
