# Generated by Django 3.0.3 on 2022-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220810_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='invoicing',
            field=models.BooleanField(default=False, verbose_name='امکان صدور فاکتور رسمی'),
        ),
    ]
