# Generated by Django 3.0.3 on 2022-07-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_city_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='city',
        ),
        migrations.AddField(
            model_name='shop',
            name='cityy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.City', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='shop',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Province', verbose_name='استان'),
        ),
    ]
