# Generated by Django 3.0.3 on 2022-07-21 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220721_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='cityy',
            new_name='city',
        ),
    ]
