# Generated by Django 3.0.3 on 2022-05-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_aaa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aaa',
        ),
    ]
