# Generated by Django 3.0.3 on 2022-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_aaa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='price_model',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=254, null=True, verbose_name='مدل قیمتی'),
        ),
    ]
