# Generated by Django 3.0.3 on 2022-07-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20220721_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Unit', verbose_name='واحد اندازه گیری'),
        ),
    ]
