# Generated by Django 3.0.3 on 2022-07-25 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20220721_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Unit', verbose_name='واحد اندازه گیری'),
        ),
    ]
