# Generated by Django 3.0.3 on 2022-07-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20220725_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='economic_code',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='کد اقتصادی'),
        ),
        migrations.AddField(
            model_name='shop',
            name='national_ID',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='شناسه ملی'),
        ),
        migrations.AddField(
            model_name='shop',
            name='registration_number',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='شماره ثبت'),
        ),
    ]
