# Generated by Django 3.0.3 on 2022-09-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerexchangenotice',
            name='answer_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('changed-value', 'changed-value')], default=1, max_length=70, verbose_name='وضعیت پاسخ'),
            preserve_default=False,
        ),
    ]
