# Generated by Django 3.0.3 on 2022-09-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerexchangenotice',
            name='date_contract',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='تاریخ قرارداد'),
        ),
    ]
