# Generated by Django 3.0.3 on 2022-11-26 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnedMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پول برگشت داده',
                'verbose_name_plural': 'پول های برگشتی',
            },
        ),
    ]
