# Generated by Django 3.0.3 on 2022-10-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerexchangenotice',
            name='answer_status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('declined', 'declined'), ('changed-value', 'changed-value')], max_length=70, null=True, verbose_name='وضعیت پاسخ'),
        ),
    ]
