# Generated by Django 3.0.3 on 2022-08-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20220815_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerexchangenotice',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
