# Generated by Django 3.0.3 on 2022-11-16 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, choices=[('خانه', 'خانه'), ('فروشگاه', 'فروشگاه'), ('انبار', 'انبار')], max_length=256, null=True, verbose_name='محل')),
                ('address', models.CharField(max_length=256, verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=256, verbose_name='شماره تماس')),
                ('postal_code', models.CharField(max_length=256, verbose_name='کد پستی')),
                ('name', models.CharField(max_length=256, verbose_name='نام تحویل گیرنده')),
                ('lname', models.CharField(max_length=256, verbose_name='نام خانوادگی تحویل گیرنده')),
                ('lat_long', models.CharField(blank=True, max_length=256, null=True, verbose_name='lat & long')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cart', 'cart'), ('ordered', 'ordered')], default='cart', max_length=30)),
                ('quantity', models.IntegerField(default=0, verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProducts', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='PostWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=60, verbose_name='روش سفارش')),
                ('price', models.IntegerField(verbose_name='هزینه ارسال')),
            ],
            options={
                'verbose_name': 'روش\u200c\u200c ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', editable=False, length=8, max_length=15, prefix='', verbose_name='کد سفارش')),
                ('delivery_date', models.CharField(max_length=256, verbose_name='تاریخ')),
                ('delivery_time', models.CharField(choices=[('۹ تا ۱۲', '۹ تا ۱۲'), ('۱۲ تا ۱۵', '۱۲ تا ۱۵'), ('۱۵ تا ۱۸', '۱۵ تا ۱۸'), ('۱۸ تا ۲۱', '۱۸ تا ۲۱')], max_length=256, verbose_name='ساعت')),
                ('pay_way', models.CharField(choices=[('online', 'پرداخت از درگاه بانکی'), ('inperson', 'پرداخت در محل')], default='online', max_length=50, verbose_name='نحوه پرداخت')),
                ('total', models.IntegerField(verbose_name='جمع مبلغ کل سفارشات')),
                ('amount', models.IntegerField(verbose_name='جمع تعداد کل سفارشات')),
                ('status', models.CharField(choices=[('New', 'در انتظار پاسخ'), ('Accepted', 'پاسخ داده شده'), ('Preparing', 'آماده سازی سفارش'), ('InPostOffice', 'تحویل به پست'), ('Arrive', 'تحویل به مشتری'), ('Canceled', 'لغو شده')], default='New', max_length=30, verbose_name='وضعیت')),
                ('admin_note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت ادمین')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Address', verbose_name='آدرس')),
                ('carts', models.ManyToManyField(to='cart.Cart', verbose_name='سبد محصولات')),
                ('post_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.PostWay', verbose_name='نحوه ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='DetermineAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'تایید موجودی'), ('not-confirmed', 'عدم موجودی')], default='New', max_length=30, verbose_name='وضعیت')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='آیتم سبد خرید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تعیین موجود بودن',
                'verbose_name_plural': 'تعیین موجود بودن کالا ها',
            },
        ),
    ]
