# Generated by Django 3.0.3 on 2022-09-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='lat_long',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='lat & long'),
        ),
        migrations.AddField(
            model_name='address',
            name='lname',
            field=models.CharField(default=1, max_length=256, verbose_name='نام خانوادگی تحویل گیرنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default=2, max_length=256, verbose_name='نام تحویل گیرنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='place',
            field=models.CharField(blank=True, choices=[('خانه', 'خانه'), ('فروشگاه', 'فروشگاه'), ('انبار', 'انبار')], max_length=256, null=True, verbose_name='محل'),
        ),
    ]
