# Generated by Django 3.0.3 on 2022-07-16 13:30

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', editable=False, length=8, max_length=15, prefix=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_way',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('credit', 'اعتباری'), ('inperson', 'حضوری')], default='online', max_length=50, verbose_name='نحوه پرداخت'),
        ),
    ]
