# Generated by Django 3.0.3 on 2022-10-10 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_salesorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetermineAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'تایید موجودی'), ('not-confirmed', 'عدم موجودی')], default='New', max_length=30, verbose_name='وضعیت')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='آیتم سبد خرید')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تعیین موجود بودن',
                'verbose_name_plural': 'تعیین موجود بودن کالا ها',
            },
        ),
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
