# Generated by Django 3.0.3 on 2022-09-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20220912_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingtime',
            name='date',
            field=models.CharField(max_length=256, verbose_name='تاریخ'),
        ),
    ]
