# Generated by Django 3.0.3 on 2022-09-12 11:25

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220912_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.CharField(default=2, max_length=256, verbose_name='تاریخ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234', editable=False, length=8, max_length=15, prefix='', verbose_name='کد سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('۹ تا ۱۲', '۹ تا ۱۲'), ('۱۲ تا ۱۵', '۱۲ تا ۱۵'), ('۱۵ تا ۱۸', '۱۵ تا ۱۸'), ('۱۸ تا ۲۱', '۱۸ تا ۲۱')], max_length=256, verbose_name='ساعت'),
        ),
        migrations.DeleteModel(
            name='ShippingTime',
        ),
    ]
