# Generated by Django 3.0.3 on 2022-10-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20221010_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'در انتظار پاسخ'), ('Accepted', 'پاسخ داده شده'), ('Preparing', 'آماده سازی سفارش'), ('InPostOffice', 'تحویل به پست'), ('Arrive', 'تحویل به مشتری'), ('Canceled', 'لغو شده')], default='New', max_length=30, verbose_name='وضعیت'),
        ),
    ]
