# Generated by Django 3.0.3 on 2022-09-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20220912_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_way',
            field=models.CharField(choices=[('online', 'پرداخت از درگاه بانکی'), ('inperson', 'پرداخت در محل')], default='online', max_length=50, verbose_name='نحوه پرداخت'),
        ),
    ]
