# Generated by Django 3.0.3 on 2022-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20220912_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('ordered', 'ordered')], default='cart', max_length=30),
        ),
    ]
