# Generated by Django 3.0.3 on 2022-06-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20220606_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='datasheet', verbose_name='فایل و Datasheet'),
        ),
    ]
