# Generated by Django 3.0.3 on 2022-06-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220608_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='fname',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='برند (فارسی)'),
        ),
        migrations.AddField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
