# Generated by Django 3.0.3 on 2022-06-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220618_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('متر', 'متر'), ('لیتر', 'لیتر'), ('کیلوگرم', 'کیلوگرم'), ('عدد', 'عدد')], max_length=256, null=True, verbose_name='واحد اندازه گیری'),
        ),
    ]
