# Generated by Django 3.0.3 on 2022-06-15 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.CharField(choices=[('۹ تا ۱۲', '۹ تا ۱۲'), ('۱۲ تا ۱۵', '۱۲ تا ۱۵'), ('۱۵ تا ۱۸', '۱۵ تا ۱۸'), ('۱۸ تا ۲۱', '۱۸ تا ۲۱')], max_length=256, verbose_name='ساعت')),
            ],
            options={
                'verbose_name': 'زمان ارسال',
                'verbose_name_plural': 'زمان ارسال',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('خانه', 'خانه'), ('فروشگاه', 'فروشگاه')], max_length=256, verbose_name='محل')),
                ('address', models.CharField(max_length=256, verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=256, verbose_name='شماره تماس')),
                ('postal_code', models.CharField(max_length=256, verbose_name='کد پستی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
