# Generated by Django 3.0.3 on 2022-06-29 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('خانه', 'خانه'), ('فروشگاه', 'فروشگاه'), ('انبار', 'انبار')], max_length=256, verbose_name='محل')),
                ('address', models.CharField(max_length=256, verbose_name='آدرس')),
                ('phone_number', models.CharField(max_length=256, verbose_name='شماره تماس')),
                ('postal_code', models.CharField(max_length=256, verbose_name='کد پستی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ShopProducts', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='PostWay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('way', models.CharField(max_length=60, verbose_name='روش سفارش')),
                ('price', models.IntegerField(verbose_name='هزینه ارسال')),
            ],
            options={
                'verbose_name': 'روش\u200c\u200c ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.CreateModel(
            name='ShippingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.CharField(choices=[('۹ تا ۱۲', '۹ تا ۱۲'), ('۱۲ تا ۱۵', '۱۲ تا ۱۵'), ('۱۵ تا ۱۸', '۱۵ تا ۱۸'), ('۱۸ تا ۲۱', '۱۸ تا ۲۱')], max_length=256, verbose_name='ساعت')),
            ],
            options={
                'verbose_name': 'زمان ارسال',
                'verbose_name_plural': 'زمان ارسال',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=10, verbose_name='کد سفارش')),
                ('pay_way', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('credit', 'اعتباری')], default='online', max_length=50, verbose_name='نحوه پرداخت')),
                ('total', models.IntegerField(verbose_name='جمع مبلغ کل سفارشات')),
                ('amount', models.IntegerField(verbose_name='جمع تعداد کل سفارشات')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('Accepted', 'تایید سفارش'), ('Preparing', 'آماده سازی سفارش'), ('InPostOffice', 'تحویل به پست'), ('Arrive', 'تحویل به مشتری'), ('Canceled', 'لغو شده')], default='New', max_length=30, verbose_name='وضعیت')),
                ('admin_note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت ادمین')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Address', verbose_name='آدرس')),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart', verbose_name='سبد محصولات')),
                ('delivery_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.ShippingTime', verbose_name='زمان تحویل')),
                ('post_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.PostWay', verbose_name='نحوه ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
