# Generated by Django 3.0.3 on 2022-06-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carts',
        ),
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ManyToManyField(to='cart.Cart', verbose_name='سبد محصولات'),
        ),
    ]
