# Generated by Django 3.0.3 on 2022-07-23 01:26

from django.db import migrations, models
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20220722_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
