# Generated by Django 3.0.3 on 2022-08-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20220820_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='answer_status',
            field=models.CharField(choices=[('New', 'جدید'), ('Accepted', 'تایید'), ('Pending', 'در حال بررسی'), ('Canceled', 'لغو شده'), ('Completed', 'به اتمام رسیده')], default='not-declinable', max_length=200, verbose_name='وضعیت پاسخ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'جدید'), ('Accepted', 'تایید'), ('Pending', 'در حال بررسی'), ('Canceled', 'لغو شده'), ('Completed', 'به اتمام رسیده')], default='New', max_length=200, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('suggestion', 'suggestion'), ('support', 'support'), ('add-attributes', 'add-attributes')], default='suggestion', max_length=200, verbose_name='نوع'),
        ),
    ]
