# Generated by Django 3.0.3 on 2022-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20220820_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='answer_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('declined', 'declined'), ('not-declinable', 'not-declinable')], default='not-declinable', max_length=200, verbose_name='وضعیت پاسخ'),
        ),
    ]
